version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    env_file:
      - elasticsearch.env
    ports:
      - 9200:9200
    volumes:
      - ${ELASTIC_DIR}:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    env_file:
      - kibana.env
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ${LOGSTASH_DIR}:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 5959:5959

