version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    env_file:
      - elasticsearch.env
    volumes:
      - ${ELASTIC_DATA_DIR}:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    env_file:
      - kibana.env
    ports:
      - 5601:5601

